/**
 *  Copyright 2017 Somnium
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.package dk.somnium.overyourclearance.client;
 */

package dk.somnium.overyourclearance;

import static dk.somnium.overyourclearance.Choice.c;
import static dk.somnium.overyourclearance.Node.n;

import java.util.Random;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.utils.IntMap;
import com.badlogic.gdx.utils.IntSet;

/**
 * Contains the state of the game world, including the current player state,
 * and the various world nodes that can be displayed.
 */
public class Model {
	
	// Special case nodes, for losing the game prematurely
	private static final int NODE_OUT_OF_CLONES=2,
							 NODE_OUT_OF_CREDITS=3;
	
	// Used plot flags
	private static final int PLOT_256 = 1,
							 PLOT_24601 = 2,
							 PLOT_101 = 3,
							 PLOT_USED_HELP = 4,
							 PLOT_INFO_1 = 5,
							 PLOT_INFO_2 = 6,
							 PLOT_BUTTON_1 = 7,
							 PLOT_BUTTON_2 = 8,
							 PLOT_BUTTON_3 = 9,
							 PLOT_BUTTON_4 = 10,
							 PLOT_FINED = 11;

	public int currentNode;
	public IntMap<Node> nodes;
	public IntSet plotpoints;
	public int maxNumberOfChoices = 0;
	
	public int numberOfClones;
	public int credits;
	public int nameIndex;
	public String name;
	
	private final String[] NAMES = {"Bob", "Jack", "Ben", "Eric", "Mark"};
//	private final String NAME_STRING = "%s-R-1GAM-%d"; No longer used 
	
	public static final Random rnd = new Random();
	
	/**
	 * Reset the player state when the game is (re)started.
	 */
	private void reset()
	{
		currentNode = 0;
		numberOfClones = 5;
		nameIndex = -1;
		credits = 1000;
		plotpoints.clear();
		calculateName();
	}
	
	/**
	 * Construct the player name, using the chosen name and the current clone number.
	 */
	private void calculateName()
	{
		String firstName = "<YOUR-NAME-HERE>";
		if (nameIndex>=0)
		{
			firstName = NAMES[nameIndex];
		}
		int currentClone = 6-numberOfClones;
		name = firstName+"-R-1GAM-"+currentClone;
//		name = String.format(NAME_STRING, firstName, currentClone);
	}
			
	public Model(GameMain theInterrogationMain) {
		nodes = new IntMap<Node>();
		plotpoints = new IntSet();
		createWorld();
		reset();
	}
	
	/**
	 * Returns the world node the player is located at.
	 * @return
	 */
	public Node getCurrentNode(){
		return nodes.get(currentNode);
	}
	
	/**
	 * Update the world and player when the player selects a choice. 
	 * @param c
	 */
	public void excecuteChoice(Choice c)
	{
		if (c != null)
		{
			currentNode = c.destination; // Move to destination node
			
			for (Effect effect : c.effects) // Apply effects.
			{
				applyEffect(effect);
			}
		}
	}
	
	/**
	 * Apply the effects of a player choice to the world.
	 * If the choice causes the player to run out of credits or clones, redirect to the relevant "game over" node.
	 * @param effect
	 */
	private void applyEffect(Effect effect)
	{
		int magnitude = effect.magnitude;
		switch (effect.type)
		{
		case CLONECHANGE:
			numberOfClones+=magnitude;
			if (numberOfClones<=0)
			{
				currentNode = NODE_OUT_OF_CLONES;
			} else
			{
				calculateName();
			}
			break;
		case CREDITCHANGE:
			credits+=magnitude;
			if (credits<0)
			{
				currentNode = NODE_OUT_OF_CREDITS;
			}
			break;
		case NAME:
			nameIndex = magnitude;
			calculateName();
			break;
		case REMOVEPLOT:
			plotpoints.remove(magnitude);
			break;
		case RESTART:
			reset();
			break;
		case SETPLOT:
			plotpoints.add(magnitude);
			break;
		default:
			break;
		}
	}
	
	/**
	 * Generate the world. In the future, this could be replaced by reading the world from a text-file generated by an external editor.
	 */
	private void createWorld()
	{
		Node node; StringBuilder sb = new StringBuilder();
		
		sb.append("A good new DayCycle to you, Citizen!\nToday is <insert-date-here>, and your location is <over-your-clearance>.\n");
		sb.append("You have been assigned to a volunteer mission of vital importance to our Friend and Leader, The Computer!\n");
		sb.append("Please state your name, for the record:");
		node = n(sb.toString(), c("My name is Bob", 1, Effect.n(0))
							  , c("My name is Jack", 1, Effect.n(1))
							  , c("My name is Ben", 1, Effect.n(2))
							  , c("My name is Eric", 1, Effect.n(3))
							  , c("My name is Mark", 1, Effect.n(4)));
		addNode(0, node);

		sb.setLength(0);
		sb.append("Very well, <name>! Please note that you have been promoted to clearance R - this means that you have access to all");
		sb.append(" equipment, locations and information with a clearance of R (RED) or below. Congratulations!\n");
		sb.append("(valid access includes clearance BLACK and RED. Access to clearances ORANGE, YELLOW, GREEN, BLUE, VIOLET and WHITE are still strictly prohibited. ");
		sb.append("Any attempt to access, enter or use information, equipment or locations above your clearance is treason, and can result in penalties such as attitude readjustment, fines, <over-your-clearance>, and/or summary termination. Thank you for your compliance, Citizen!)\n");
		sb.append("As part of your promotion, you have also been assigned 4 extra clones, as well as 1000 credits. Running out of either is treason!\n");
		sb.append("\nCitizen <name>, please report to room BFG-X-*bzzzrt* immediately for your briefing!");
		node = n(sb.toString(), c("Hire a TaxiBot for BFG-X-256 (100 credits)", 14, Requirement.np(PLOT_256) ,Effect.cr(-100), Effect.pa(PLOT_256)),
								c("Hire a TaxiBot for BFG-X-24601 (100 credits)", 15, Requirement.np(PLOT_24601) ,Effect.cr(-100), Effect.pa(PLOT_24601)),
								c("Hire a TaxiBot for BFG-X-451 (100 credits)", 16, Effect.cr(-100)),
								c("Hire a TaxiBot for BFG-X-101 (100 credits)", 13, Requirement.np(PLOT_101) ,Effect.cr(-100), Effect.pa(PLOT_101)),
								c("Contact the Computer help-line for assistance", 5, Requirement.np(PLOT_USED_HELP), Effect.pa(PLOT_USED_HELP)),
								c("Contact the Computer help-line again for assistance", 4, Requirement.p(PLOT_USED_HELP))
				);
		addNode(1, node);
		
		node = n("Citizen! It seems that you have run out of clones, and are therefore unable to continue your mission! Maybe the next volunteer will be more dilligent in his service to The Computer, and less wasteful with important human resources...",
				c("New Citizen reporting for duty!", 0, Effect.restart()));
		addNode(NODE_OUT_OF_CLONES, node);
		
		node = n("Citizen! It seems that you have run out of credits. A security bot has been dispatched to your location. It will escort you to the nearest recycling station. Here you shall be re-integrated into the resource base, to cover your debt to society. Thank you for your compliance, Citizen!",
				c("Thank you, Friend Computer!", 0, Effect.restart()));
		addNode(NODE_OUT_OF_CREDITS, node);
		
		node = n("Thank you for calling my help-line, Citizen <name>! I regret to inform you that you have used all of your help-quota for this DayCycle. You are therefore fined 100 credits for unauthorized use of Computer resources. Have a nice day, Citizen!",
				c("Thank you, Friend Computer!", 12, Effect.cr(-100)));
		addNode(4, node);
		
		sb.setLength(0);
		sb.append("Thank you for calling my help-line, Citizen <name>!\n");
		sb.append("\nCurrent help-line efficiency statistics indicate, that 73% of all Citizens calling the help-line for assistance, never place another call.\n");
		sb.append("\nPlease - specify - how - I - may - assist - you - this - day - Citizen:\n");
		sb.append("To report yourself for treason, press 1\n");
		sb.append("To report another Citizen for treason, press 2\n");
		sb.append("For inquries about assigned missions, press 10\n");
		node = n(sb.toString(), c("Press 1 to report yourself for treason", 6),
				                c("Press 2 to report a citizen for treason",7),
				                c("Press 10 for mission assistance.", 6));
		addNode(5, node);
		
		sb.setLength(0);
		sb.append("You have selected:  1 - report yourself for treason.\n");
		sb.append("Remain where you are - a SecBot will be with you shortly.\n");
		sb.append("Thank you for your co-operation, Citizen!\n");
		node = n(sb.toString(), c("Await your summary termination.", 12, Effect.cl(-1)));
		addNode(6, node);

		sb.setLength(0);
		sb.append("You have selected:  2 - report another Citizen for treason.\n");
		sb.append("Please state the name of the Citizen in question.");
		node = n(sb.toString(), c("<name>", 8, Effect.cr(200)),
                c("John-Doe-1",9, Effect.cr(200)),
                c("Who-R-YOU", 9, Effect.cr(200)));
		addNode(7, node);
		
		sb.setLength(0);
		sb.append("Thank you for your dilligence, Citizen <name>! You have been awarded 200 credits.\n");
		sb.append("<INTERCOM>: Citizen <name>, please report to the nearest Termination Booth! Thank you for your complicance!");
		node = n(sb.toString(), c("Report to the nearest Termination Booth", 12, Effect.cl(-1)));
		addNode(8, node);

		sb.setLength(0);
		sb.append("Thank you for your dilligence, Citizen <name>! You have been awarded 200 credits.\n");
		sb.append("Please select your reason for waiting until now to report this serious transgression:\n");
		sb.append("To confess to be the traitor's collaborator, press 1\n");
		sb.append("To confess to have been negligent in your reporting duties, press 2\n");
		sb.append("To state that you just learned about this treason, press 10\n");
		node = n(sb.toString(), c("Press 1 to confess to be a collaborator.", 11),
                c("Press 2 to confess to negligence in your duties.",10, Effect.cr(-100), Effect.pa(PLOT_FINED)),
                c("Press 10 to state that you just learned of the treason.", 11));
		addNode(9, node);
		
		sb.setLength(0);
		sb.append("You have selected - 2 - confess to negligence in your duties.\n");
		sb.append("This is troubling news, Citizen <name>! You have been fined 100 credits for this dereliction of duty. I trust that you shall be more dilligent in the future!");
		node = n(sb.toString(), c("I shall, Friend Computer!", 12));
		addNode(10, node);

		sb.setLength(0);
		sb.append("You have selected - 1 - confess to collaboration with traitors.\n");
		sb.append("Please report to your nearest security office, for a complimentary invasive mindprobe.");
		node = n(sb.toString(), c("Obey Friend Computer.", 12, Effect.cl(-1)));
		addNode(11, node);
	
		sb.setLength(0);
		sb.append("You consider the best way to get to the briefing room.");
		node = n(sb.toString(), c("Hire a TaxiBot for BFG-X-256 (100 credits)", 14, Requirement.np(PLOT_256) ,Effect.cr(-100), Effect.pa(PLOT_256)),
								c("Hire a TaxiBot for BFG-X-24601 (100 credits)", 15, Requirement.np(PLOT_24601) ,Effect.cr(-100), Effect.pa(PLOT_24601)),
								c("Hire a TaxiBot for BFG-X-451 (100 credits)", 16, Effect.cr(-100)),
								c("Hire a TaxiBot for BFG-X-101 (100 credits)", 13, Requirement.np(PLOT_101) ,Effect.cr(-100), Effect.pa(PLOT_101)),
								c("Contact the Computer help-line for assistance", 5, Requirement.np(PLOT_USED_HELP), Effect.pa(PLOT_USED_HELP)),
								c("Contact the Computer help-line again for assistance", 4, Requirement.p(PLOT_USED_HELP))
				);
		addNode(12, node);
		
		sb.setLength(0);
		sb.append("As the taxi bot unceremoniously ejects you at your destination, ");
		sb.append("you notice with some consternation that you have been dropped of at a ");
		sb.append("clearance BLUE plaza. It seems that you are currently interrupting a parade of BLUE security officers.\n");
		sb.append("As the officers enthusiastically administer a suitable punishment for your transgression, your final thoughts ");
		sb.append("goes to a loud admiration of their weapon skills.");
		node = n(sb.toString(), c("Glory to the protectors of our society! My next clone will be less disruptive.", 12, Effect.cl(-1)));
		addNode(13, node);
		
		sb.setLength(0);
		sb.append("As the taxi bot unceremoniously ejects you at your destination, ");
		sb.append("you find yourself in the middle of a dining hall for workers. The location seems to be the site of a food fight of immense proportions,");
		sb.append("and you are pelted with AlgaeFun (tm) from head to toe before you manage to fight your way out.");
		node = n(sb.toString(), c("Pay 200 credits for a throrough cleansing.",12,Effect.cr(-200)),
				                c("Jump into the nearest incinerator. Cleanliness is mandatory!", 12, Effect.cl(-1)));
		addNode(14, node);
		
		sb.setLength(0);
		sb.append("As the taxi bot unceremoniously ejects you at your destination, ");
		sb.append("you look around. You seem to be standing in a large area littered with debris and craters. ");
		sb.append("It would appear that you are standing in the middle of a testing room for advanced weaponry. As you realize the ");
		sb.append("implications of this fact, your thoughts on the fragility of existence is rudely interrupted, as the output from a VIOLET multi-laser prototype mk. 3 turns you into a fine red mist (at least the mist is within your security clearance). ");
		sb.append("\nYour diligence in weapons testing is commendable, Citizen, but in this case you have other business to attend to!");
		node = n(sb.toString(), c("Scientific research is vital to our society! My next clone will take care of the other business.", 12, Effect.cl(-1)));
		addNode(15, node);

		sb.setLength(0);
		sb.append("As the taxi bot unceremoniously ejects you at your destination, ");
		sb.append("you find yourself in a small room. A man in a green jumpsuit greets you.");
		sb.append("Greetings <name>. Four other Citizens were supposed to join you on your mission, but unfortunately, none of them made it.");
		sb.append("\n\nNot to worry, though. I'm sure that you will be able handle it on your own. I am BILL-G-REEN-2, and I'll be your briefing officer for this mission. Please, have a seat Citizen.");
		node = n(sb.toString(), c("Sit down in one of the empty seats", 17));
		addNode(16, node);
		
		sb.setLength(0);
		sb.append("Your mission is simple: Field testing of one of R&D's newest inventions.\n");
		sb.append("You'll test the device, and then report back the results to me.\n");
		sb.append("Also, ensure that the device is not harmed during the testing.\n");
		sb.append("Do you have any further questions, Citizen?\n");
		node = n(sb.toString(), c("What can you tell me about the device?", 18, Requirement.np(PLOT_INFO_1), Effect.pa(PLOT_INFO_1)),
								c("What can you tell me about R&D?", 18, Requirement.np(PLOT_INFO_2), Effect.pa(PLOT_INFO_2)),
								c("I do not, Citizen! I'll go to R&D now (hiring a 100 credit taxi cab)", 21, Effect.cr(-100)));
		addNode(17, node);
		
		node = n("I'm afraid that further information on that topic is above your clearance level, citizen.",
				c("Surely, an exception could be made for such an important mission?", 19),
				c("I understand, Citizen!", 17));
		addNode(18, node);
		
		sb.setLength(0);
		sb.append("Your statement indicates, that you either disagree with the Computer's assessment of the clearance level of the requested information, ");
		sb.append("or that you are attempting to gain access to information above your clearance.\n\nBoth are acts of treason. You are fined 500 credits.");
		node = n(sb.toString(), c("Thank you for the attitude correction, Citizen!", 17, Effect.cr(-500), Effect.pa(PLOT_FINED)),
								c("This is an outrage! I demand the information necessary to do my job!", 20, Effect.cr(-500), Effect.pa(PLOT_FINED)));
		addNode(19, node);
		
		node = n("In accordance with his directives, and not at all just because he felt like it, Bill shoots you with his trusty GREEN laser for that treasonous outburst.",
				c("My next clone will be better behaved, I hope", 17, Effect.cl(-1)));
		addNode(20, node);
		
		sb.setLength(0);
		sb.append("You arrive at the R&D labs. The area is bustling with activity, and the sounds of humming machinery, <over-your-clearance>, explosions and the enthusiastic screaming of volunteers fill the air.");
		sb.append("\n\nA row of ten counters serve all Citizens who have business with R&D. A long line of low-clearance workers stretches from the entrance of the labs and all the way to the only counter which is not closed due to the clerk being on a break.");
		sb.append("\n\nA sign at the front states, that in order to facilitate shorter waiting times, an efficiency surcharge of 10 credits per minute will be charged to all Citizens standing in line.");
		node = n(sb.toString(), c("Stand at the back of the line as a good Citizen", 22, Effect.cr(-10)),
				c("Pull rank, using your RED clearance to move to the front of the line.", 23));
		addNode(21, node);
		
		node = n("You have waited for a minute in the line, and 10 credits have been deducted from your account.",
				c("<wait>", 22, Effect.cr(-10)),
				c("Pull rank, using your RED clearance to move to the front of the line.", 23));
		addNode(22, node);
		
		sb.setLength(0);
		sb.append("Flashing your clearance RED access card, you move to the head of the line. The tight smiles on the faces of the other citizens as you pass them, is of course due to their courteous nature, and not because Happiness is Mandatory.\n");
		sb.append("\nThe clerk greets you warmly, and asks you to follow him to the lab, as he closes down the last counter. The remaining workers in the line look suspiciously unhappy as this happens.");
		node = n(sb.toString(), c("Follow the clerk", 25), c("Remind the unhappy workers in the line, that Happiness is Mandatory.", 24));
		addNode(23, node);
		
		node = n("For no apparent reason, the treasonous workers crowd around you, leaving the line in a distressing state of disarray. Then they tear you apart, in clear violation of the rule of which you so kindly reminded them.",
				c("At least my next clone will already be at the R&D labs.", 25, Effect.cl(-1)));
		addNode(24, node);
		
		sb.setLength(0);
		sb.append("In the lab, the clerk proudly shows you a small metallic box, with several buttons on its otherwise featureless surface.\n\n");
		sb.append("This is the Scienceinator 9000, Citizen <name>! Please take good care of it during your testing! I suggest testing the device in dining hall E115");
		node = n(sb.toString(), c("Ask for instructions on how to use the device.", 26),
				c("Ask about the screams from the volunteer department.", 27),
				c("Travel to dining hall E115 immediately, hiring a Taxi Bot (100 credits)", 28, Effect.cr(-100)));
		addNode(25, node);
		
		node = n("I'm sorry Citizen <name>, but all records and blueprints concerning the S-9000 was lost, along with its inventor and most of sector A112, during his last experiment.",
				c("Travel to dining hall E115, hiring a Taxi Bot (100 credits)", 28, Effect.cr(-100)));
		addNode(26, node);
		
		node = n("You are mistaken, Citizen. No one is screaming. Happiness is Mandatory!", c("Travel to dining hall E115, hiring a Taxi Bot (100 credits)", 28, Effect.cr(-100)));
		addNode(27, node);
		
		sb.setLength(0);
		sb.append("As the taxi bot unceremoniously ejects you at your destination, ");
		sb.append("you look around you, and see several groups of low clearance citizens sitting in the dining hall, while peacefully enjoying their meals.");
		sb.append("You place the S-9000 on the floor, and prepare to commence your experiments.");
		node = n(sb.toString(), c("Press the triangular button", 29, Requirement.np(PLOT_BUTTON_1), Effect.pa(PLOT_BUTTON_1)),
								c("Press the square button", 30, Requirement.np(PLOT_BUTTON_2), Effect.pa(PLOT_BUTTON_2)),
								c("Press the circular button", 31, Effect.pa(PLOT_BUTTON_4)),
								c("Press the star shaped button", 32, Requirement.np(PLOT_BUTTON_3), Effect.pa(PLOT_BUTTON_3)),
								c("Hire a Taxi Bot to bring you back to BFG-X-451 for debriefing (100 credits)", 34, Effect.cr(-100))
								);
		addNode(28, node);
		
		sb.setLength(0);
		sb.append("A robotic voice emanates from somwhere inside the device:\n");
		sb.append("You have selected: 'BioDisassemble nearest target' Thank you for using the Sciencinator 9000, material recycler edition.\n\n");
		sb.append("A strange ray shoots from the device, disassembling you into energy which is rapidly absorbed by the device. The last thing you hear, is the robotic voice: 'The intrinsic value of the target has been credited to your account'.");
		node = n(sb.toString(), c("Note to self: Don't stand near experimental R&D equipment when it is activated.", 33, Effect.cl(-1), Effect.cr(200)));
		addNode(29, node);
		
		sb.setLength(0);
		sb.append("A robotic voice emanates from somwhere inside the device:\n");
		sb.append("You have selected: 'BioDisassemble nearest low-clearance target' Thank you for using the Sciencinator 9000, material recycler edition.\n\n");
		sb.append("A strange ray shoots from the device, hitting a nearby lunching worker. Before the eyes of you and the horrified Citizens at his table, he is disassembled into energy, which is rapidly absorbed by the device.\n\nWhen only his clothes remain, the robotic voice states: 'The intrinsic value of the target has been credited to your account'.");
		node = n(sb.toString(), c("For Science!", 33, Effect.cr(200)));
		addNode(30, node);
		
		sb.setLength(0);
		sb.append("A robotic voice emanates from somwhere inside the device:\n");
		sb.append("Self-destruction protocol initiated. Releasing all stored energy!\n\n");
		sb.append("As the S-9000 explodes, it vaporizes itself, you, the dining-hall, all the diners, and the subsector.");
		node = n(sb.toString(), c("Oops... Well, at least I won't have to pay for taxi service to the debriefing room then...", 34, Effect.cl(-1)));
		addNode(31, node);
		
		sb.setLength(0);
		sb.append("A robotic voice emanates from somwhere inside the device:\n");
		sb.append("You have selected: 'BioReassemble' Thank you for using the Sciencinator 9000, material recycler edition. You will be charged for the intrinsic value of the created target.\n\n");
		sb.append("A whole Citizen's worth of biological matter sprays from the machine, covering a group of nearby diners. They are promptly run over by a over-enthusiastic ScrubBot which as it scrambles to clean the mess.");
		node = n(sb.toString(), c("I suppose a mess hall is an appropriate place for a mess.", 33, Effect.cr(-200)));
		addNode(32, node);
		
		sb.setLength(0);
		sb.append("The somewhat alarmed Citizens hunch over their meals, in an attempt to keep a low profile while your experiments continue.");
		node = n(sb.toString(), c("Press the triangular button", 29, Requirement.np(PLOT_BUTTON_1), Effect.pa(PLOT_BUTTON_1)),
				c("Press the square button", 30, Requirement.np(PLOT_BUTTON_2), Effect.pa(PLOT_BUTTON_2)),
				c("Press the circular button", 31, Effect.pa(PLOT_BUTTON_4)),
				c("Press the star shaped button", 32, Requirement.np(PLOT_BUTTON_3), Effect.pa(PLOT_BUTTON_3)),
				c("Hire a Taxi Bot to bring you back to BFG-X-451 for debriefing (100 credits)", 34, Effect.cr(-100))
				);
		addNode(33, node);

		sb.setLength(0);
		sb.append("As you arrive for your debriefing, BILL-G-REEN-2 looks sternly at you.");
		sb.append("\nYou certainly took your time, Citizen <name>! Now, let us review the mission footage.\n\n<debriefing>");
		node = n(sb.toString(), c("Start over", 0, Effect.restart()));
		addNode(34, node);
	}
	
	private void addNode(int id, Node node)
	{
		if (nodes.containsKey(id))
		{
			System.out.println("Node already exists!");
			Gdx.app.exit();
		}
		nodes.put(id, node);
		if (node.choices.size>maxNumberOfChoices) maxNumberOfChoices = node.choices.size;
	}

	/**
	 * Evaluate whether a given requirement for a choice selection is fulfilled.
	 * If not, the choice should not be displayed to the player.
	 * @param req
	 * @return
	 */
	public boolean evaluateRequirement(Requirement req) {
		boolean meetsRequirement = false;
		if (req == null)
		{
			meetsRequirement = true;
		} else
		{
			int magnitude = req.magnitude;
			switch (req.requirement)
			{
			case MINCREDITS:
				meetsRequirement = (credits>=magnitude);
				break;
			case NOPLOT:
				meetsRequirement = !plotpoints.contains(magnitude);
				break;
			case PLOT:
				meetsRequirement = plotpoints.contains(magnitude);
				break;
			default:
				break;
			}
		}
		return meetsRequirement;
	}
	
	final static String[] waitTexts = {"Keep waiting - patience is good Citizenship", "Keep waiting, I think the line moved a bit", "Keep waiting, humming softly to pass the time", "Keep waiting - the other Citizens were here first", "Keep waiting - eventually, my turn will come", "Keep waiting - patience is a virtue", "Keep waiting - my turn is bound to come up any time now", "Keep waiting - I have already spent credits on standing in line, so I might as well stay a bit longer", "Keep waiting - an orderly line is the responsibility of every good Citizen"};

	/**
	 * Generates a random line for the "<wait>" special token. 
	 * @return
	 */
	public static String generateRandomWaitText() {
		return waitTexts[rnd.nextInt(waitTexts.length)]; 
	}

	/**
	 * Generates the text for the "<debriefing>" special token, i.e. how well the player did.
	 * @return
	 */
	public String generateDebriefing() {
		StringBuilder sb = new StringBuilder();
		int completedTestsCount = 0;
		if (plotpoints.contains(PLOT_BUTTON_1))
		{
			completedTestsCount++;
		}
		if (plotpoints.contains(PLOT_BUTTON_2))
		{
			completedTestsCount++;
		}
		if (plotpoints.contains(PLOT_BUTTON_3))
		{
			completedTestsCount++;
		}
		if (plotpoints.contains(PLOT_BUTTON_4))
		{
			// Mission failure. Blew up the device.
			sb.append("Citizen, your mission was a disaster! Any test results you might have accomplished, have ben rended moot, since you managed to destroy the device. And the fact that you are also responsible for the destruction of an entire subsector, as well as all of the Computer's property within, only makes matters worse!\n\n");
			sb.append("Therefore, you are hereby stripped of your RED clearance, and are reassigned to the weapon testing labs as a test subject, effective immediately. Additionally, you are hereby fined 500 credits, for being in a briefing room of clearance RED.\n\nTrust the Computer! The Computer is your friend!");
		} else if (completedTestsCount == 3)
		{
			// Perfect test. Final rating depends on what else happened.
			if (!plotpoints.contains(PLOT_FINED) && numberOfClones == 4)
			{
				// Perfect run
				sb.append("Citizen, you are to be commended for your perfect performance! Not only did you return with comprehensive test results, but you also managed to do so without transgressing against the rules of our society, and without unathorized waste of clones!\n\n");
				sb.append("For this impressive performance, you are promoted to Clearance ORANGE, and are awarded a bonus of 10.000 credits!\n\n");
				sb.append("However, due to the extremely low probabilty of a perfectly completed mission, you have also been flagged for an additional investigation. Please report to the nearest confession booth, for a throrough scrutiny of your actions from birth and until this moment.");
			} else
			{
				// Excellent run
				sb.append("Citizen, you are to be commended for your stellar performance! Your comprehensive test results are certain to assist R&D in perfecting the device!!\n\n");
				sb.append("For this excellent performance, you are awawrded a bonus of 5.000 credits!\n\n");
			}
		} else if (completedTestsCount == 0)
		{
		    // Mission failure. No tests performed.
			// Mission failure. Blew up the device.
			sb.append("Citizen, you have failed your mission! Without any completed tests, R&D are no closer to understanding the device.\n\n");
			sb.append("Therefore, you are hereby stripped of your RED clearance, and are reassigned to the food processing department as a food vat cleaner, effective immediately. Additionally, you are hereby fined 500 credits, for being in a briefing room of clearance RED.\n\nTrust the Computer! The Computer is your friend!");
		} else
		{
			// Partial success. Performed some experiments.
			sb.append("Citizen, your performance have been deemed to be adequate. Your partial test results will still be useful for the researchers, and at least you managed to deliver it back in one piece.\n\n");
			sb.append("For this performance, you are awarded a bonus of 2.000 credits!\n\n");
		}
		return sb.toString();
	}
}
